# Generated by Django 3.1.7 on 2021-04-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('address', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=500)),
                ('lastName', models.TextField(max_length=500)),
                ('email', models.TextField(max_length=500)),
                ('phone', models.TextField(max_length=10)),
                ('password', models.TextField(max_length=50)),
                ('role', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=5)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('coffeeBar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.coffeebar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.user')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('coffeeBar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.coffeebar')),
            ],
        ),
    ]
