# Generated by Django 3.1.7 on 2021-05-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210516_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('coffee_bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.coffeebar')),
            ],
        ),
    ]
