# Generated by Django 3.1.7 on 2021-05-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20210516_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeebar',
            name='image',
            field=models.ImageField(null=True, upload_to='coffee_bars'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menus'),
        ),
    ]
